#!/usr/bin/env python
import os

Import("env")

BINDIR = "bin"

# For the reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags
tests_env = env.Clone()

SConscript("deps/SCsub", {"env": tests_env})

tests_env.unit_test = tests_env.BuildUnitTest(
    target=os.path.join(BINDIR, "openvic-dataloader"),
    src_dir="src",
    defines_prefix="openvic_dataloader",
)

Return("tests_env")
