name: 🔢 Build Matrix

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-matrix:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: windows-debug
            os: windows-latest
            name: 🏁 Windows Debug
            target: template_debug
            platform: windows
            arch: x86_64
            test-bin-suffix: .md.exe

          - identifier: windows-debug-mingw
            os: windows-latest
            name: 🏁 Windows Debug (MinGW)
            target: template_debug
            platform: windows
            arch: x86_64
            mingw: true
            test-bin-suffix: .md.exe

          - identifier: windows-debug-replace
            os: windows-latest
            name: 🏁 Windows Debug (Replace Error UTF Compliance)
            target: template_debug
            platform: windows
            arch: x86_64
            compliance_type: error_replace
            test-bin-suffix: .md.exe

          - identifier: windows-release
            os: windows-latest
            name: 🏁 Windows Release
            target: template_release
            platform: windows
            arch: x86_64
            test-bin-suffix: .md.exe

          - identifier: windows-release-mingw
            os: windows-latest
            name: 🏁 Windows Release (MinGW)
            target: template_release
            platform: windows
            arch: x86_64
            mingw: true
            test-bin-suffix: .md.exe

          - identifier: macos-debug
            os: macos-latest
            name: 🍎 macOS (universal) Debug
            target: template_debug
            platform: macos
            arch: universal

          - identifier: macos-debug-replace
            os: macos-latest
            name: 🍎 macOS (universal) Debug (Replace Error UTF Compliance)
            target: template_debug
            platform: macos
            compliance_type: error_replace
            arch: universal

          - identifier: macos-release
            os: macos-latest
            name: 🍎 macOS (universal) Release
            target: template_release
            platform: macos
            arch: universal

          - identifier: linux-debug
            os: ubuntu-22.04
            name: 🐧 Linux Debug
            target: template_debug
            platform: linux
            arch: x86_64

          - identifier: linux-debug-replace
            os: ubuntu-22.04
            name: 🐧 Linux Debug (Replace Error UTF Compliance)
            target: template_debug
            platform: linux
            compliance_type: error_replace
            arch: x86_64

          - identifier: linux-debug-error
            os: ubuntu-22.04
            name: 🐧 Linux Debug (Build Error UTF Compliance)
            target: template_debug
            platform: linux
            compliance_type: error
            arch: x86_64

          - identifier: linux-release
            os: ubuntu-22.04
            name: 🐧 Linux Release
            target: template_release
            platform: linux
            arch: x86_64

    steps:
      - name: Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false

      - name: Setup MinGW for Windows/MinGW build
        if: matrix.platform == 'windows' && (matrix.mingw || false)
        uses: egor-tensin/setup-mingw@0ea9f5370e9405e1b4cc436a2668226b02450eb2

      - name: Build
        uses: ./.github/actions/openvic-dl-build
        with:
          identifier: ${{ matrix.identifier }}
          target: ${{ matrix.target }}
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          compliance-type: ${{ matrix.compliance_type || 'loose' }}

      - name: Run tests
        run: |
          ./tests/bin/openvic-dataloader.tests.${{ matrix.platform }}.${{ matrix.target }}.${{ matrix.arch }}${{ matrix.test-bin-suffix || '' }}
