name: 🔢 Build Matrix

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-matrix:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: windows-debug
            os: windows-latest
            name: 🏁 Windows Debug
            preset: windows-x64-md
            configuration: Debug
            target: template_debug

          - identifier: windows-debug-replace
            os: windows-latest
            name: 🏁 Windows Debug (Replace Error UTF Compliance)
            preset: windows-x64-md
            configuration: Debug
            target: template_debug
            compliance_type: error_replace

          - identifier: windows-release
            os: windows-latest
            name: 🏁 Windows Release
            preset: windows-x64-md
            configuration: Release
            target: template_release

          - identifier: macos-debug
            os: macos-latest
            name: 🍎 macOS (universal) Debug
            preset: macos-universal
            configuration: Debug
            target: template_debug

          - identifier: macos-debug-replace
            os: macos-latest
            name: 🍎 macOS (universal) Debug (Replace Error UTF Compliance)
            preset: macos-universal
            configuration: Debug
            target: template_debug
            compliance_type: error_replace

          - identifier: macos-release
            os: macos-latest
            name: 🍎 macOS (universal) Release
            preset: macos-universal
            configuration: Release
            target: template_release

          - identifier: linux-debug
            os: ubuntu-22.04
            name: 🐧 Linux Debug
            preset: linux-x64
            configuration: Debug
            target: template_debug

          - identifier: linux-debug-replace
            os: ubuntu-22.04
            name: 🐧 Linux Debug (Replace Error UTF Compliance)
            preset: linux-x64
            configuration: Debug
            target: template_debug
            compliance_type: error_replace

          - identifier: linux-debug-error
            os: ubuntu-22.04
            name: 🐧 Linux Debug (Build Error UTF Compliance)
            preset: linux-x64
            configuration: Debug
            target: template_debug
            compliance_type: error

          - identifier: linux-release
            os: ubuntu-22.04
            name: 🐧 Linux Release
            preset: linux-x64
            configuration: Release
            target: template_release

    steps:
      - name: Checkout project
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Build
        uses: ./.github/actions/openvic-dl-build
        with:
          identifier: ${{ matrix.identifier }}
          preset: ${{ matrix.preset }}
          configuration: ${{ matrix.configuration }}
          target: ${{ matrix.target }}
          compliance-type: ${{ matrix.compliance_type || 'loose' }}
