name: 🚀 Releases

on:
  push:
    tags: ["v*"]

permissions: {}

env:
  SEMVER_REGEX: ^v(0|[1-9][0-9]*)((\.(0|[1-9][0-9]*)){1,2})(-(alpha|beta|rc)\.([1-9][0-9]*))?$
  SEMVER_SNAPSHOT_REGEX: ^v(0|[1-9][0-9]*)((\.(0|[1-9][0-9]*)){1,2})-(snapshot|snapshot\.dev)\.([1-9][0-9]*)\+([0-9a-fA-F]{40})$

jobs:
  static-checks-release:
    name: Code style, file formatting, and docs
    if: vars.DISABLE_TAG_RELEASES != true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Treeless clone. Slightly less performant than a shallow clone, but makes finding diffs instantaneous.
          filter: tree:0 # See: https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/
          persist-credentials: false

      - name: Validate tag
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          validate_version () {
            [[ $1 =~ $SEMVER_REGEX ]] && return
            [[ $1 =~ $SEMVER_SNAPSHOT_REGEX ]] && return

            echo "::error::${2:-parameter} is not a valid semver string for versioning starting with v. Valid prerelease values are 'alpha', 'beta', 'rc', 'snapshot', and 'snapshot.dev'. A count value must follow all prerelease tags, starting from 1. 'snapshot' and 'snapshot.dev' must include the full commit SHA as a build string"
            false
          }

          if ! validate_version "$GITHUB_REF_NAME" "github.ref (tag)"; then
            exit 1
          fi

      - name: Install APT dependencies
        uses: awalsh128/cache-apt-pkgs-action@553a35bb8ebd9fcabcb1c9451aa4c98e1b4ca8a9 # v1.6.3
        with:
          packages: libxml2-utils

      - name: Style checks via prek
        uses: j178/prek-action@5337cb91e0fa35a7ff31b9ca345126d8bbbcdf16 # v2.0.6

  build-release:
    name: ${{ matrix.name }} Release
    needs: static-checks-release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - identifier: windows-release
            os: windows-latest
            name: 🏁 Build Windows
            target: template_release
            platform: windows
            arch: x86_64
            scons-flags: ''

          - identifier: macos-release
            os: macos-latest
            name: 🍎 Build macOS
            target: template_release
            platform: macos
            arch: universal
            scons-flags: lto=full

          - identifier: linux-release
            os: ubuntu-latest
            name: 🐧 Build Linux
            runner: ubuntu-22.04
            target: template_release
            platform: linux
            arch: x86_64
            scons-flags: lto=full use_static_cpp=yes

    steps:
      - name: Checkout project
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false

      - name: Build
        uses: ./.github/actions/openvic-dl-build
        with:
          identifier: ${{ matrix.identifier }}
          target: ${{ matrix.target }}
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          disable-cache: true
          scons-flags: use_hot_reload=no build_ovdl_tests=no ${{ matrix.scons-flags }}

  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: build-release
    permissions:
      contents: write  # May be needed to publish release
    env:
      IS_PRERELEASE: ${{
          contains(github.ref, '-alpha') ||
          contains(github.ref, '-beta') ||
          contains(github.ref, '-rc') ||
          contains(github.ref, '-snapshot')
        }}
      IS_SNAPSHOT: ${{ contains(github.ref, '-snapshot') }}
    steps:
      - name: Shallow Clone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1 # See: https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/
          persist-credentials: false

      - name: Get FROM_REF
        env:
          GH_TOKEN: ${{ github.token }}
          EXCLUDE_PRE_RELEASES: ${{ !env.IS_PRERELEASE && '--exclude-pre-releases' || '' }}
          EXCLUDE_SNAPSHOTS: ${{ !env.IS_SNAPSHOT && '| select(.tagName | contains("-snapshot") | not)' || '' }}
        run:
          echo "FROM_REF=$(gh release list $EXCLUDE_PRE_RELEASES --json tagName --jq "[.[] $EXCLUDE_SNAPSHOTS.tagName][0]")" >> $GITHUB_ENV

      - name: Publish Release
        uses: ./.github/actions/openvic-dl-release
        with:
          latest: ${{ !env.IS_PRERELEASE && !env.IS_SNAPSHOT }}
          prerelease: ${{ env.IS_PRERELEASE }}
          snapshot-release: ${{ env.IS_SNAPSHOT }}
          from-ref: ${{ env.FROM_REF || vars.DEFAULT_COMMIT_HASH }}
          src-token: ${{ secrets.GITHUB_TOKEN }}
